### ISSUE TITLE
DiscretizedMoveItIKSolver not found

### ISSUE THREAD

**Issue by collinthornton** [marip8/reach_roscon_2023#4]
The DiscretizedMoveItIKSolver is not exported as an available REACH IK plugin. 

Here's my YAML config:
```
ik_solver:
  name: DiscretizedMoveItIKSolver
  distance_threshold: 0.0
  planning_group: *planning_group
  collision_mesh_filename: *collision_mesh_filename
  touch_links: []
```

Here's the program output:
```
cthornton@c18105:~/roscon2023/workshop/colcon_ws $ ros2 launch reach_ros start.launch.py results_dir:=/tmp config_name:=study_3
[INFO] [launch]: All log files can be found below /home/D10.US.SWRI.ORG/cthornton/.ros/log/2023-10-13-11-04-08-009343-c18105-23036
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [reach_ros_node-1]: process started with pid [23039]
[reach_ros_node-1] Failed to create plugin instance 'DiscretizedMoveItIKSolver' of type 'reach::IKSolverFactory'
[reach_ros_node-1] Search Paths (including system folders)
[reach_ros_node-1] Search Libraries:
[reach_ros_node-1]     - libreach_plugins.so
[reach_ros_node-1]     - libreach_ros_plugins.so
[reach_ros_node-1] Available plugins of type 'reach::IKSolverFactory':
[reach_ros_node-1]     - NoOpIKSolver
[reach_ros_node-1]     - MoveItIKSolver
[reach_ros_node-1]     - DiscretizedMoveItIKSolverFactory
[reach_ros_node-1] 
```

I traced the error back to a plugin export in `reach_ros2`. See https://github.com/ros-industrial/reach_ros2/issues/31.
